export default {
  id: "commandcode",
  priority: 100,
  alias: "commandcode",
  aliases: [
    "cmc",
  ],
  uiAlias: "cmc",
  display: {
    name: "Command Code",
    icon: "smart_toy",
    color: "#000000",
    textIcon: "CC",
    website: "https://commandcode.ai",
    notice: {
      text: "Use your CommandCode CLI API key (starts with user_...) from ~/.commandcode/auth.json or commandcode.ai/studio. Go plan only has /alpha/generate (no Provider API).",
      apiKeyUrl: "https://commandcode.ai/studio",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.commandcode.ai/alpha/generate",
    format: "commandcode",
    forceStream: true,
    headers: {
      "x-command-code-version": "0.25.7",
      "x-cli-environment": "cli",
    },
    usage: {
      url: "https://api.commandcode.ai/alpha/billing/credits",
      subscriptionsUrl: "https://api.commandcode.ai/alpha/billing/subscriptions",
    },
  },
  features: {
    usage: true,
    usageApikey: true,
  },
  // Go plan catalog: https://commandcode.ai/docs/plans/go (33 models, /alpha/generate only)
  models: [
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", contextLength: 1000000 },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp", contextLength: 1000000 },
    { id: "moonshotai/Kimi-K3", name: "Kimi K3", contextLength: 1000000 },
    { id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code", contextLength: 256000 },
    { id: "moonshotai/Kimi-K2.7-Code-Highspeed", name: "Kimi K2.7 Code HighSpeed", contextLength: 262000 },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6", contextLength: 256000 },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5", contextLength: 256000 },
    { id: "zai-org/GLM-5.3", name: "GLM 5.3", contextLength: 1000000 },
    { id: "zai-org/GLM-5.2", name: "GLM 5.2", contextLength: 1000000 },
    { id: "zai-org/GLM-5.2-Fast", name: "GLM 5.2 Fast", contextLength: 1000000 },
    { id: "zai-org/GLM-5.1", name: "GLM 5.1", contextLength: 200000 },
    { id: "zai-org/GLM-5", name: "GLM 5", contextLength: 200000 },
    { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3", contextLength: 1000000 },
    { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7", contextLength: 200000 },
    { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5", contextLength: 200000 },
    { id: "Qwen/Qwen3.8-Max", name: "Qwen 3.8 Max", contextLength: 1000000 },
    { id: "Qwen/Qwen3.7-Max", name: "Qwen 3.7 Max", contextLength: 1000000 },
    { id: "Qwen/Qwen3.7-Plus", name: "Qwen 3.7 Plus", contextLength: 1000000 },
    { id: "Qwen/Qwen3.7-Flash", name: "Qwen 3.7 Flash", contextLength: 1000000 },
    { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max Preview", contextLength: 200000 },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus", contextLength: 200000 },
    { id: "stepfun/Step-3.7-Flash", name: "Step 3.7 Flash", contextLength: 256000 },
    { id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash", contextLength: 1000000 },
    { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro", contextLength: 1000000 },
    { id: "xiaomi/mimo-v2.5", name: "MiMo V2.5", contextLength: 1000000 },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", contextLength: 1000000 },
    { id: "tencent/hy3-paid", name: "Tencent Hy3", contextLength: 262144 },
    { id: "poolside/laguna-s-2.1-free", name: "Laguna S 2.1", contextLength: 256000 },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", contextLength: 1050000 },
    { id: "xai/grok-4.5", name: "Grok 4.5", contextLength: 500000 },
    { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor", contextLength: 1048576 },
    { id: "thinkingmachines/inkling", name: "Inkling", contextLength: 256000 },
    { id: "thinkingmachines/inkling-small", name: "Inkling Small", contextLength: 1000000 },
  ],
};
