export default {
  id: "grok-web",
  priority: 150,
  alias: "grok-web",
  aliases: [
    "gw",
  ],
  uiAlias: "gw",
  display: {
    name: "Grok Web (Subscription)",
    icon: "auto_awesome",
    color: "#1DA1F2",
    textIcon: "GW",
    website: "https://grok.com",
  },
  category: "webCookie",
  authType: "cookie",
  // grok2api-compatible: bare JWT is enough (sso-rw is mirrored server-side).
  // Full header also accepted: sso=...; sso-rw=...; cf_clearance=...
  authHint: "Paste sso JWT from grok.com (or full cookie: sso=...; sso-rw=...). Optional CF cookies via providerSpecificData.cloudflareCookies.",
  transport: {
    baseUrl: "https://grok.com/rest/app-chat/conversations/new",
    format: "grok-web",
    authType: "cookie",
  },
  models: [
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini (Thinking)" },
    { id: "grok-3-thinking", name: "Grok 3 Thinking" },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-mini", name: "Grok 4 Mini (Thinking)" },
    { id: "grok-4-thinking", name: "Grok 4 Thinking" },
    { id: "grok-4-heavy", name: "Grok 4 Heavy (SuperGrok)" },
    { id: "grok-4.1-mini", name: "Grok 4.1 Mini (Thinking)" },
    { id: "grok-4.1-fast", name: "Grok 4.1 Fast" },
    { id: "grok-4.1-expert", name: "Grok 4.1 Expert" },
    { id: "grok-4.1-thinking", name: "Grok 4.1 Thinking" },
    { id: "grok-4.2", name: "Grok 4.2 (4.20 Beta)" },
    { id: "grok-4.5", name: "Grok 4.5 (alias → fast)" },
    { id: "grok-chat-fast", name: "Grok Chat Fast" },
    { id: "grok-chat-auto", name: "Grok Chat Auto" },
    { id: "grok-chat-expert", name: "Grok Chat Expert" },
    { id: "grok-chat-heavy", name: "Grok Chat Heavy" },
  ],
  passthroughModels: true,
};
