import { buildKiroCliChatHeaders } from "../../config/kiroClient.js";

export default {
  id: "kiro",
  priority: 10,
  alias: "kr",
  uiAlias: "kr",
  display: {
    name: "Kiro AI",
    icon: "psychology_alt",
    color: "#FF6B35",
    website: "https://kiro.dev",
    notice: {
      signupUrl: "https://kiro.dev",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  category: "free",
  transport: {
    baseUrl: "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
    baseUrls: [
      "https://runtime.us-east-1.kiro.dev/generateAssistantResponse",
      "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
      "https://q.us-east-1.amazonaws.com/generateAssistantResponse",
    ],
    format: "kiro",
    retry: {
      "429": 0,
    },
    // kiro-cli identity, captured from a live kiro-cli 2.24.1 request — see
    // config/kiroClient.js. Both the chat and control-plane UA strings are the
    // real CLI's own values, so an account never presents the desktop-IDE
    // fingerprint.
    headers: {
      "Content-Type": "application/x-amz-json-1.0",
      Accept: "*/*",
      ...buildKiroCliChatHeaders(),
    },
    tokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authUrl: "https://prod.us-east-1.auth.desktop.kiro.dev",
    usage: {
      cwHost: "https://codewhisperer.us-east-1.amazonaws.com",
      qHost: "https://q.us-east-1.amazonaws.com",
      limitsPath: "/getUsageLimits",
    },
  },
  models: [
    // The upstream catalog: the 20 models ListAvailableModels returns for a live
    // account, carrying the rate/context metadata that response reports. Kiro's
    // own default is `auto` — it picks the model server-side.
    { id: "auto", name: "Auto (Kiro Agent)", rateMultiplier: 1, contextLength: 1000000, maxOutput: 64000, description: "Models chosen by task for optimal usage and consistent quality" },
    { id: "auto-thinking", name: "Auto (Kiro Agent) (Thinking)", upstreamModelId: "auto", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1, description: "Models chosen by task for optimal usage and consistent quality" },
    { id: "claude-opus-5.5", name: "Claude Opus 5.5", upstreamModelId: "claude-opus-5.5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2, description: "Kiro claude-opus-5.5 — 2x credit, 1000k context" },
    { id: "claude-opus-5.5-thinking", name: "Claude Opus 5.5 (Thinking)", upstreamModelId: "claude-opus-5.5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2, description: "Kiro claude-opus-5.5 — 2x credit, 1000k context" },
    { id: "claude-opus-5.5-agentic", name: "Claude Opus 5.5 (Agentic)", upstreamModelId: "claude-opus-5.5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2, description: "Kiro claude-opus-5.5 — 2x credit, 1000k context" },
    { id: "claude-opus-5.5-thinking-agentic", name: "Claude Opus 5.5 (Thinking + Agentic)", upstreamModelId: "claude-opus-5.5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2, description: "Kiro claude-opus-5.5 — 2x credit, 1000k context" },
    { id: "claude-opus-5", name: "Claude Opus 5", upstreamModelId: "claude-opus-5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-5 — 2.2x credit, 1000k context" },
    { id: "claude-opus-5-thinking", name: "Claude Opus 5 (Thinking)", upstreamModelId: "claude-opus-5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-5 — 2.2x credit, 1000k context" },
    { id: "claude-opus-5-agentic", name: "Claude Opus 5 (Agentic)", upstreamModelId: "claude-opus-5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-5 — 2.2x credit, 1000k context" },
    { id: "claude-opus-5-thinking-agentic", name: "Claude Opus 5 (Thinking + Agentic)", upstreamModelId: "claude-opus-5", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-5 — 2.2x credit, 1000k context" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", upstreamModelId: "claude-sonnet-5", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-5 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-5-thinking", name: "Claude Sonnet 5 (Thinking)", upstreamModelId: "claude-sonnet-5", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-5 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-5-agentic", name: "Claude Sonnet 5 (Agentic)", upstreamModelId: "claude-sonnet-5", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-5 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-5-thinking-agentic", name: "Claude Sonnet 5 (Thinking + Agentic)", upstreamModelId: "claude-sonnet-5", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-5 — 1.3x credit, 1000k context" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8", upstreamModelId: "claude-opus-4.8", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.8 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.8-thinking", name: "Claude Opus 4.8 (Thinking)", upstreamModelId: "claude-opus-4.8", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.8 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.8-agentic", name: "Claude Opus 4.8 (Agentic)", upstreamModelId: "claude-opus-4.8", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.8 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.8-thinking-agentic", name: "Claude Opus 4.8 (Thinking + Agentic)", upstreamModelId: "claude-opus-4.8", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.8 — 2.2x credit, 1000k context" },
    { id: "gpt-5.6-sol", name: "Gpt 5.6 Sol", upstreamModelId: "gpt-5.6-sol", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 4.4, description: "Kiro gpt-5.6-sol — 4.4x credit, 1000k context" },
    { id: "gpt-5.6-sol-thinking", name: "Gpt 5.6 Sol (Thinking)", upstreamModelId: "gpt-5.6-sol", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 4.4, description: "Kiro gpt-5.6-sol — 4.4x credit, 1000k context" },
    { id: "gpt-5.6-sol-agentic", name: "Gpt 5.6 Sol (Agentic)", upstreamModelId: "gpt-5.6-sol", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 4.4, description: "Kiro gpt-5.6-sol — 4.4x credit, 1000k context" },
    { id: "gpt-5.6-sol-thinking-agentic", name: "Gpt 5.6 Sol (Thinking + Agentic)", upstreamModelId: "gpt-5.6-sol", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 4.4, description: "Kiro gpt-5.6-sol — 4.4x credit, 1000k context" },
    { id: "gpt-5.6-terra", name: "Gpt 5.6 Terra", upstreamModelId: "gpt-5.6-terra", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro gpt-5.6-terra — 2.2x credit, 1000k context" },
    { id: "gpt-5.6-terra-thinking", name: "Gpt 5.6 Terra (Thinking)", upstreamModelId: "gpt-5.6-terra", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro gpt-5.6-terra — 2.2x credit, 1000k context" },
    { id: "gpt-5.6-terra-agentic", name: "Gpt 5.6 Terra (Agentic)", upstreamModelId: "gpt-5.6-terra", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro gpt-5.6-terra — 2.2x credit, 1000k context" },
    { id: "gpt-5.6-terra-thinking-agentic", name: "Gpt 5.6 Terra (Thinking + Agentic)", upstreamModelId: "gpt-5.6-terra", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro gpt-5.6-terra — 2.2x credit, 1000k context" },
    { id: "gpt-5.6-luna", name: "Gpt 5.6 Luna", upstreamModelId: "gpt-5.6-luna", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 1.1, description: "Kiro gpt-5.6-luna — 1.1x credit, 1000k context" },
    { id: "gpt-5.6-luna-thinking", name: "Gpt 5.6 Luna (Thinking)", upstreamModelId: "gpt-5.6-luna", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 1.1, description: "Kiro gpt-5.6-luna — 1.1x credit, 1000k context" },
    { id: "gpt-5.6-luna-agentic", name: "Gpt 5.6 Luna (Agentic)", upstreamModelId: "gpt-5.6-luna", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 1.1, description: "Kiro gpt-5.6-luna — 1.1x credit, 1000k context" },
    { id: "gpt-5.6-luna-thinking-agentic", name: "Gpt 5.6 Luna (Thinking + Agentic)", upstreamModelId: "gpt-5.6-luna", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 1.1, description: "Kiro gpt-5.6-luna — 1.1x credit, 1000k context" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7", upstreamModelId: "claude-opus-4.7", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.7 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.7-thinking", name: "Claude Opus 4.7 (Thinking)", upstreamModelId: "claude-opus-4.7", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.7 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.7-agentic", name: "Claude Opus 4.7 (Agentic)", upstreamModelId: "claude-opus-4.7", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.7 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.7-thinking-agentic", name: "Claude Opus 4.7 (Thinking + Agentic)", upstreamModelId: "claude-opus-4.7", contextLength: 1000000, maxOutput: 128000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.7 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6", upstreamModelId: "claude-opus-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.6 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.6-thinking", name: "Claude Opus 4.6 (Thinking)", upstreamModelId: "claude-opus-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.6 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.6-agentic", name: "Claude Opus 4.6 (Agentic)", upstreamModelId: "claude-opus-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.6 — 2.2x credit, 1000k context" },
    { id: "claude-opus-4.6-thinking-agentic", name: "Claude Opus 4.6 (Thinking + Agentic)", upstreamModelId: "claude-opus-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.6 — 2.2x credit, 1000k context" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", upstreamModelId: "claude-sonnet-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.6 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-4.6-thinking", name: "Claude Sonnet 4.6 (Thinking)", upstreamModelId: "claude-sonnet-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.6 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-4.6-agentic", name: "Claude Sonnet 4.6 (Agentic)", upstreamModelId: "claude-sonnet-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.6 — 1.3x credit, 1000k context" },
    { id: "claude-sonnet-4.6-thinking-agentic", name: "Claude Sonnet 4.6 (Thinking + Agentic)", upstreamModelId: "claude-sonnet-4.6", contextLength: 1000000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.6 — 1.3x credit, 1000k context" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5", upstreamModelId: "claude-opus-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.5 — 2.2x credit, 200k context" },
    { id: "claude-opus-4.5-thinking", name: "Claude Opus 4.5 (Thinking)", upstreamModelId: "claude-opus-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.5 — 2.2x credit, 200k context" },
    { id: "claude-opus-4.5-agentic", name: "Claude Opus 4.5 (Agentic)", upstreamModelId: "claude-opus-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.5 — 2.2x credit, 200k context" },
    { id: "claude-opus-4.5-thinking-agentic", name: "Claude Opus 4.5 (Thinking + Agentic)", upstreamModelId: "claude-opus-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 2.2, description: "Kiro claude-opus-4.5 — 2.2x credit, 200k context" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", upstreamModelId: "claude-sonnet-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.5 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 (Thinking)", upstreamModelId: "claude-sonnet-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.5 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4.5-agentic", name: "Claude Sonnet 4.5 (Agentic)", upstreamModelId: "claude-sonnet-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.5 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4.5-thinking-agentic", name: "Claude Sonnet 4.5 (Thinking + Agentic)", upstreamModelId: "claude-sonnet-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4.5 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4", upstreamModelId: "claude-sonnet-4", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4-thinking", name: "Claude Sonnet 4 (Thinking)", upstreamModelId: "claude-sonnet-4", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4-agentic", name: "Claude Sonnet 4 (Agentic)", upstreamModelId: "claude-sonnet-4", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4 — 1.3x credit, 200k context" },
    { id: "claude-sonnet-4-thinking-agentic", name: "Claude Sonnet 4 (Thinking + Agentic)", upstreamModelId: "claude-sonnet-4", contextLength: 200000, maxOutput: 64000, rateMultiplier: 1.3, description: "Kiro claude-sonnet-4 — 1.3x credit, 200k context" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", upstreamModelId: "claude-haiku-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.4, description: "Kiro claude-haiku-4.5 — 0.4x credit, 200k context" },
    { id: "claude-haiku-4.5-thinking", name: "Claude Haiku 4.5 (Thinking)", upstreamModelId: "claude-haiku-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.4, description: "Kiro claude-haiku-4.5 — 0.4x credit, 200k context" },
    { id: "claude-haiku-4.5-agentic", name: "Claude Haiku 4.5 (Agentic)", upstreamModelId: "claude-haiku-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.4, description: "Kiro claude-haiku-4.5 — 0.4x credit, 200k context" },
    { id: "claude-haiku-4.5-thinking-agentic", name: "Claude Haiku 4.5 (Thinking + Agentic)", upstreamModelId: "claude-haiku-4.5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.4, description: "Kiro claude-haiku-4.5 — 0.4x credit, 200k context" },
    { id: "deepseek-3.2", name: "Deepseek 3.2", upstreamModelId: "deepseek-3.2", contextLength: 164000, maxOutput: 64000, rateMultiplier: 0.25, strip: ["image", "audio"], description: "Kiro deepseek-3.2 — 0.25x credit, 164k context" },
    { id: "deepseek-3.2-thinking", name: "Deepseek 3.2 (Thinking)", upstreamModelId: "deepseek-3.2", contextLength: 164000, maxOutput: 64000, rateMultiplier: 0.25, strip: ["image", "audio"], description: "Kiro deepseek-3.2 — 0.25x credit, 164k context" },
    { id: "deepseek-3.2-agentic", name: "Deepseek 3.2 (Agentic)", upstreamModelId: "deepseek-3.2", contextLength: 164000, maxOutput: 64000, rateMultiplier: 0.25, strip: ["image", "audio"], description: "Kiro deepseek-3.2 — 0.25x credit, 164k context" },
    { id: "deepseek-3.2-thinking-agentic", name: "Deepseek 3.2 (Thinking + Agentic)", upstreamModelId: "deepseek-3.2", contextLength: 164000, maxOutput: 64000, rateMultiplier: 0.25, strip: ["image", "audio"], description: "Kiro deepseek-3.2 — 0.25x credit, 164k context" },
    { id: "minimax-m2.5", name: "Minimax M2.5", upstreamModelId: "minimax-m2.5", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.25, description: "Kiro minimax-m2.5 — 0.25x credit, 196k context" },
    { id: "minimax-m2.5-thinking", name: "Minimax M2.5 (Thinking)", upstreamModelId: "minimax-m2.5", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.25, description: "Kiro minimax-m2.5 — 0.25x credit, 196k context" },
    { id: "minimax-m2.5-agentic", name: "Minimax M2.5 (Agentic)", upstreamModelId: "minimax-m2.5", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.25, description: "Kiro minimax-m2.5 — 0.25x credit, 196k context" },
    { id: "minimax-m2.5-thinking-agentic", name: "Minimax M2.5 (Thinking + Agentic)", upstreamModelId: "minimax-m2.5", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.25, description: "Kiro minimax-m2.5 — 0.25x credit, 196k context" },
    { id: "minimax-m2.1", name: "Minimax M2.1", upstreamModelId: "minimax-m2.1", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.15, description: "Kiro minimax-m2.1 — 0.15x credit, 196k context" },
    { id: "minimax-m2.1-thinking", name: "Minimax M2.1 (Thinking)", upstreamModelId: "minimax-m2.1", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.15, description: "Kiro minimax-m2.1 — 0.15x credit, 196k context" },
    { id: "minimax-m2.1-agentic", name: "Minimax M2.1 (Agentic)", upstreamModelId: "minimax-m2.1", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.15, description: "Kiro minimax-m2.1 — 0.15x credit, 196k context" },
    { id: "minimax-m2.1-thinking-agentic", name: "Minimax M2.1 (Thinking + Agentic)", upstreamModelId: "minimax-m2.1", contextLength: 196000, maxOutput: 64000, rateMultiplier: 0.15, description: "Kiro minimax-m2.1 — 0.15x credit, 196k context" },
    { id: "glm-5", name: "Glm 5", upstreamModelId: "glm-5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.5, description: "Kiro glm-5 — 0.5x credit, 200k context" },
    { id: "glm-5-thinking", name: "Glm 5 (Thinking)", upstreamModelId: "glm-5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.5, description: "Kiro glm-5 — 0.5x credit, 200k context" },
    { id: "glm-5-agentic", name: "Glm 5 (Agentic)", upstreamModelId: "glm-5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.5, description: "Kiro glm-5 — 0.5x credit, 200k context" },
    { id: "glm-5-thinking-agentic", name: "Glm 5 (Thinking + Agentic)", upstreamModelId: "glm-5", contextLength: 200000, maxOutput: 64000, rateMultiplier: 0.5, description: "Kiro glm-5 — 0.5x credit, 200k context" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next", upstreamModelId: "qwen3-coder-next", contextLength: 256000, maxOutput: 64000, rateMultiplier: 0.05, strip: ["image", "audio"], description: "Kiro qwen3-coder-next — 0.05x credit, 256k context" },
    { id: "qwen3-coder-next-thinking", name: "Qwen3 Coder Next (Thinking)", upstreamModelId: "qwen3-coder-next", contextLength: 256000, maxOutput: 64000, rateMultiplier: 0.05, strip: ["image", "audio"], description: "Kiro qwen3-coder-next — 0.05x credit, 256k context" },
    { id: "qwen3-coder-next-agentic", name: "Qwen3 Coder Next (Agentic)", upstreamModelId: "qwen3-coder-next", contextLength: 256000, maxOutput: 64000, rateMultiplier: 0.05, strip: ["image", "audio"], description: "Kiro qwen3-coder-next — 0.05x credit, 256k context" },
    { id: "qwen3-coder-next-thinking-agentic", name: "Qwen3 Coder Next (Thinking + Agentic)", upstreamModelId: "qwen3-coder-next", contextLength: 256000, maxOutput: 64000, rateMultiplier: 0.05, strip: ["image", "audio"], description: "Kiro qwen3-coder-next — 0.05x credit, 256k context" },
  ],
  oauth: {
    ssoOidcEndpoint: "https://oidc.us-east-1.amazonaws.com",
    registerClientUrl: "https://oidc.us-east-1.amazonaws.com/client/register",
    deviceAuthUrl: "https://oidc.us-east-1.amazonaws.com/device_authorization",
    tokenUrl: "https://oidc.us-east-1.amazonaws.com/token",
    startUrl: "https://view.awsapps.com/start",
    clientName: "kiro-oauth-client",
    clientType: "public",
    scopes: [
      "codewhisperer:completions",
      "codewhisperer:analysis",
      "codewhisperer:conversations",
    ],
    grantTypes: [
      "urn:ietf:params:oauth:grant-type:device_code",
      "refresh_token",
    ],
    issuerUrl: "https://identitycenter.amazonaws.com/ssoins-722374e8c3c8e6c6",
    socialAuthEndpoint: "https://prod.us-east-1.auth.desktop.kiro.dev",
    socialLoginUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/login",
    socialTokenUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/oauth/token",
    socialRefreshUrl: "https://prod.us-east-1.auth.desktop.kiro.dev/refreshToken",
    authMethods: [
      "builder-id",
      "idc",
      "google",
      "github",
      "import",
    ],
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
